
default: &default
  adapter: postgresql
  encoding: unicode
  database: contactbook
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  


development:
  <<: *default

test:
  <<: *default

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>